from features import *
from RIS import RIS

def runTable1():
    print("Entered CIT mode. We will now simulate the test suite of Table 1, generated by CIT.")
    print("Note that test number 4 detects the interaction error, and you can visually see in the GUI that all instructions are not displayed.")
    RISsystem = RIS()
    testSuite = ["+Widget, +Instructions, +InstrColdweather,  +EmergencyLevel, +Low",
                 "-InstructionsColdweather, -Low, +InstructionsFlood, +High",
                 "-Instructions, -InstructionsFlood, +Map",
                 "+Instructions, +InstructionsFlood, +InstructionsColdweather, +Low",
                 "-InstructionsFlood, -High",
                 "-Instructions, -InstructionsColdweather, -Low",
                 "+Low",
                 "+High"]
    iter = 1
    for transitions in testSuite:
        print("================= Test number " + str(iter) + "================================")
        valid = RISsystem.transition(transitions)
        if valid:
            print("Current emergency level : " + str(RISsystem.emergencyLevel))
        answer = input("Please enter anything to transition to the next test configuration, or \"exit\" to stop the simulation.")
        if answer.lower() == "exit":
            break
        iter += 1


def runTransitionError():
    print("Entered transition mode.")
    RISsystem = RIS()
    iter = 1
    print("================= Test number " + str(iter) + "================================")
    RISsystem.transition("+Widget, +emergencylevel, +high, +map")
    print("Current emergency level : " + str(RISsystem.emergencyLevel))
    print("-----------")
    print("We will first perform the transition \"-high, +low\", which should trigger an error as described in Section 2 of the paper.")
    answer = input("Please enter anything to perform the transition \"-high, +low\", or \"exit\" to stop the simulation.")
    if answer.lower() == "exit":
        return
    iter += 1
    print("================= Test number " + str(iter) + "================================")
    RISsystem.transition("-high, +low")
    print("Current emergency level : " + str(RISsystem.emergencyLevel))
    print("-----------")
    print("We now demonstrate the other problematic transition : \"-Map, +Instructions\".")
    answer = input("Please enter anything to perform the transition \"-Map, +Instructions\", or \"exit\" to stop the simulation.")
    if answer.lower() == "exit":
        return
    iter += 1
    print("================= Test number " + str(iter) + "================================")
    RISsystem.transition("-Map, +Instructions")
    print("Current emergency level : " + str(RISsystem.emergencyLevel))

    print("This ends this short demonstration. Feel free to explore the possible configurations with the free mode.")
    print("As shown in the paper, you can for example achieve the same final state +Widget, +emergencylevel, +low, +map (Test number 2) by any other transitions, and see that there is no error.")
    input("Enter anything to terminate execution.")

def runFreeMode():
    print("Entered free mode.")
    print("The expected transitions between configurations is a list of features that are activated ('+') or deactivated ('-'), separated by commas.")
    print("Example : \"+widget, +emergencylevel, +Map\" (we advise to start with this transition to achieve a valid system state.)")
    print("Note that the (de)activations are automatically ordered and the features' names are not case sensitive. \"Instructions\" can be abbreviated to \"Instr\".")
    RISsystem = RIS()
    iter = 1
    while True:
        print("================= Test number " + str(iter) + "================================")
        answer = input("Please enter transition to be executed, or \"exit\" to terminate execution :")
        if answer.lower() == "exit":
            return
        RISsystem.transition(answer)
        print("Current emergency level : " + str(RISsystem.emergencyLevel))
        iter += 1


print("Welcome to this little demonstration on transition behavioural errors.")
print("Please read the README to understand the three modes proposed, then type the mode you wish to run between \"CIT\", \"transition\" and \"free\".")
choice = input()
while choice not in ["CIT", "transition", "free"]:
    print("The mode was not recognized. Please choose among \"CIT\", \"transition\" and \"free\".")
    choice = input()
if "CIT" in choice:
    runTable1()
elif "transition" in choice:
    runTransitionError()
elif "free" in choice:
    runFreeMode()
